### ISSUE TITLE
question about un-official Resnet

### ISSUE THREAD

**Issue by lijiaoyang** [Mephisto405/Learning-Loss-for-Active-Learning#17]
Thanks for your paper and code!
I have a question, why you don't use the  [torch official resnet](https://github.com/pytorch/vision/blob/main/torchvision/models/resnet.py).
In your [ResNet](https://github.com/Mephisto405/Learning-Loss-for-Active-Learning/blob/master/models/resnet.py), kernel_size=3, stride=1, padding=1
But in torch official resnet, kernel_size=7, stride=2, padding=3
Can you explain it? Thanks!

**Comment by Mephisto405** [comment]
![image](https://user-images.githubusercontent.com/25499931/175230019-4dfab8ce-221c-49a1-8593-a2abe6d1b32e.png)
The official paper has the answer to your question! :)
