### ISSUE TITLE
About the performance of active learning methods

### ISSUE THREAD

**Issue by Kyle-YK-Yu** [Mephisto405/Learning-Loss-for-Active-Learning#7]
I try some methods including random, entropy, core-set, VAAL and yours with Resnet-18 on Cifar-100 using fixed initial indices. But icannot get an ideal result. Random, entropy, VAAL and LL4AL have the almost same accuracies. Is this possible? I check my settings many times.

**Comment by Mephisto405** [comment]
Yeah, please take a look at this issue: [The test accuracy is not matched with your image.](https://github.com/Mephisto405/Learning-Loss-for-Active-Learning/issues/2)

In fact, I think LL4AL only achieves comparable or slightly better results. Main advantage besides the performance is its **task-agnostic nature**.
